### ISSUE TITLE
DarkRaider's Stock To-Do List

### ISSUE THREAD

**Issue by km00700** [TeamOpenIndustry/ImmersiveRailroading#370]
My latest list has moved:
[Trello Page](https://trello.com/b/wDz2iM9B/darkraiders-to-do-list)

**Locomotives:**
- [x] F150 Hi-Rail
- [x] F59PHI (Surfliner Scheme)
- [x] F59PHI (Cascades Scheme)
- [x] F59PHI (Amtrak California Scheme)
- [x] ES44AC/DC
- [ ] P42DC
- [ ] F40PH
- [ ] SD70MAC
- [ ] DDA40X
- [ ] SIEMENS SC44 Dumpsterfire

**Passenger Cars:**
- [x] Superliner Coach (Phase IVb)
- [x] Superliner Diner (Phase IVb)
- [x] Superliner Lounge (Phase IVb)
- [ ] Superliner Sleeper (Phase IVb)
- [ ] Superliner Transition Sleeper (Phase IVb)
- [x] Superliner Coach Wreck Rebuild (Surfliner Scheme)
- [x] Superliner Coach Wreck Rebuild (Amtrak California Scheme)
- [x] Surfliner Coach
- [ ] Surfliner Cafe
- [x] Surfliner Cabcar
- [ ] Talgo Generator/Baggage (Cascades Scheme)
- [ ] Talgo Coach (Cascades Scheme)
- [ ] Talgo Diner (Cascades Scheme)
- [ ] Talgo Bistro (Cascades Scheme)
- [ ] Phase V Amfleet Daycoach

**Freight Cars:**
- [ ] Amtrak Heritage Baggage (Phase IVb)
- [ ] Flatcar
- [ ] DOT 111 Tank Car
