### ISSUE TITLE
TheGibster's Rolling Stock To-Do List

### ISSUE THREAD

**Issue by DerGibster** [TeamOpenIndustry/ImmersiveRailroading#541]
Rolling stock listed here will be done at my discretion and is subject to change. 

**Locomotives:**

- [x] - Reading RR 0-4-0 Camelback
- [ ] - Generic 2-6-0 Mogul
- [ ] - Baldwin 2-6-6-2 Logging Mallet (Needs oil-burning code)
- [ ] - Quincy RR 2-6-2T (Needs oil-burning code)
- [ ] - Chinese SY Class / JF6 Mikaro
- [ ] - Chinese KD7 Class
- [x] - Fairmont Rail Speeder
- [x] - EM Baldwin 2' Gauge Diesel
- [ ] - GE U30b diesel
- [ ] - EMD MP15 Road Switcher

**Freight Cars:**

- [x] - Ortner Gravel Hopper Car
- [x] - 41' Steel Gondola
- [x] - Helium Tank Car
- [ ] - Wood-sided Gondola
- [ ] - Refrigerator Car
- [ ] - Large Coal Hopper
- [ ] - Ore Car
- [ ] - Centerbeam Flat Car

**Passenger Cars:**

- [x] - Bay Window Caboose
- [x] - Extended Vision Caboose (x2)
- [x] - Standard Cupola Caboose
- [ ] - Earlier Wood-sided or combination cabooses
- [ ] - A proper set of Pullman Heavyweight coaches (In the REALLY far future)
- [ ] - "Ferdinand Magellan" Armored Pullman Car (Also hard, but a little more feasible)
