### ISSUE TITLE
Milkypenguin's To-Do List

### ISSUE THREAD

**Issue by Milkypenguin** [TeamOpenIndustry/ImmersiveRailroading#542]
Here's my up to date to-do list. I'm doing stuff on this list at my discretion and everything here is subject to change. This list is not in order of competition, but I'll try and update projects with a % done next to them that have some progress done on them as I work on them.
**Standard Gauge:**

**Steam:**
- [ ] 70 Ton Logging 2-8-2 with Normal and Vanderbilt tenders - 20%
- [ ] Logging 2-6-2 - 55%
- [ ] Sierra Railway 4-6-0 3 -0%
- [ ] Sierra Railway 2-8-0 18 - 0%
- [ ] Western Pacific TP-29 4-6-0 - 0%
- [ ] Western Pacific 0-6-0 163 Series - 0%
- [ ] Virginia & Truckee 2-6-0 20 Tahoe - 25%

**Diesels:**
- [ ] EMD SD9 - 0%
- [ ] EMD SD7 - 0%
- [ ] EMD SW1 - 45%(Being Rebuilt)

 **Electrics**
- [x] Portland Traction Company Brill Master Unit - 100%, waiting for electric code
- [x] Portland Traction Company Line Car 1058 - 100%, waiting for electric code 
- [ ] Portland Traction Company 1065 Series Interurban Car - 20%
- [ ] Sydney Tramways Class O - 0%
- [ ] Baldwin 40 Ton Steeple Cab Locomotive - 0%
- [ ] Portland Traction Company/Pacific Electric Hollywood Car - 0%

**Rolling Stock:**
- [ ] Sierra Railway Coaches - 0%
- [ ] SP C-30-1 Caboose - 80%
- [ ] SP&S 700 Series Caboose - 80%

**Misc:**
- [x] Speeder and Cart - 100%

**42in Gauge:**

**Trolleys:**
- [ ] Portland Traction Company 500 Series Trolley - 0%
- [ ] Portland Traction Company Class H - 0%

**Narrow Gauge (3 foot):**

**Steam:**
- [x] D&RGW C-16 268 - 100%
- [ ] D&RGW C-16 1880’s - 95%
- [ ] D&RGW T-12 1940's- 30%
- [ ] Hawaii Railway Co 5 - 95%
- [ ] North Pacific Coast 4-4-0 “Cab Forward” 21 - 40%
- [ ] Oregon Lumber Company Climax - 0%
- [ ] Oregon Lumber Company Shay - 0%
- [ ] Sumpter Valley 50 4-6-0 - 60%
- [ ] Sumpter Valley ALCO 2-8-2 - 60%
- [ ] Sumpter Valley Baldwin 2-8-2 - 0%
- [ ] Sumpter Valley 2-6-6-2 - 20%
- [ ] Uintah Railway Shay - 0%
- [ ] Uintah Railway 0-6-2t - 95%
- [ ] Uintah Railway 51 2-6-6-2t - 95%
- [ ] W.H. Eccles Lumber Co. Heisler 3 - 0%
- [ ] White Pass & Yukon T Class 4-6-0 62(Inside Frame) - 40%
- [ ] White Pass & Yukon T Class 4-6-0 (Outside Frame) - 0%
- [ ] White Pass & Yukon 2-8-0 61 - 20%

**Diesels:**
- [x] Sumpter Valley 100 - 100%
- [x] Sumpter Valley 101 - 100%

**Rolling Stock:**
- [x] D&RGW Silver Vista - 100%
- [ ] DSP&P Tiffany Reefer - 95%
- [ ] Sumpter Valley Coach Set(5 cars) - 60%
- [ ] Sumpter Valley Caboose - 95%
- [ ] Sumpter Valley Reefer - 95%
- [ ] Sumpter Valley Box Car - 95%
- [ ] WP&Y Baggage Car 205 - 95%
- [ ] WP&Y Open Air Observation Car 230 - 95%
- [ ] WP&Y Observation Car “Lake Fraser” - 0%

**Misc:**
- [ ] Sumpter Valley Mail Motorcar 14 and Mail Cart 15 - 50%
